# Generated by Django 3.1 on 2020-09-20 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productEnquiries', '0003_auto_20200907_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenquiries',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
