# Generated by Django 3.1 on 2020-08-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blogsImage',
            field=models.ImageField(null=True, upload_to='uploads/blogs/'),
        ),
    ]
