# Generated by Django 3.1 on 2020-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_blogsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.TextField(default='John Doe'),
        ),
    ]
