# Generated by Django 3.1 on 2020-08-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200818_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='upload',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
