# Generated by Django 3.1 on 2020-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200818_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='upload',
        ),
    ]
