# Generated by Django 3.1 on 2020-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_categories_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categoriesIconImage',
            field=models.ImageField(null=True, upload_to='uploads/categories/'),
        ),
    ]
