# Generated by Django 3.1 on 2020-09-20 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_categories_categoriesiconimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='categories',
            name='createdBy',
            field=models.TextField(default='John Doe'),
        ),
    ]
