# Generated by Django 3.1 on 2020-09-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
