# Generated by Django 3.1 on 2020-08-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoterequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='fullName',
            field=models.CharField(max_length=120),
        ),
    ]
