# Generated by Django 3.1 on 2020-09-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoterequest', '0002_auto_20200826_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
