# Generated by Django 3.1 on 2020-09-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoterequest', '0003_quoterequest_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='phoneNo',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
