# Generated by Django 3.1 on 2020-09-07 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200905_0623'),
        ('quoterequest', '0004_quoterequest_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoterequests', to='products.product'),
        ),
    ]
