# Generated by Django 3.1 on 2020-09-20 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoterequest', '0006_remove_quoterequest_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
